# Generated by Django 5.0.4 on 2024-04-30 17:49

import apps.products.models.products
import core.misc.utils
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Fecha de actualización')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Fecha de creación')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de eliminación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('serial', models.CharField(blank=True, max_length=8)),
                ('name', models.CharField(max_length=100, validators=[core.misc.utils.validate_char_field], verbose_name='Nombre')),
                ('category_name', models.CharField(max_length=100, verbose_name='Nombre de Categoría')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('image', models.ImageField(blank=True, upload_to=apps.products.models.products.upload_file_path, verbose_name='Imágen')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio')),
                ('qty', models.IntegerField(blank=True, null=True, verbose_name='Cantidad')),
                ('description', models.CharField(blank=True, max_length=500, null=True, validators=[core.misc.utils.validate_char_field], verbose_name='Descripción')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.categories', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'products',
            },
        ),
    ]
