# Generated by Django 5.0.4 on 2024-04-30 17:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='serial',
        ),
        migrations.AddField(
            model_name='products',
            name='sdk',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
