# Generated by Django 5.0.4 on 2024-04-30 17:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_products_serial_products_sdk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='sdk',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
