# Generated by Django 5.0.4 on 2024-04-30 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='total_views',
            field=models.IntegerField(default=1),
        ),
    ]
