# Generated by Django 5.0.4 on 2024-04-30 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_track_total_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
    ]
