# Generated by Django 5.0.4 on 2024-04-30 17:37

import apps.categories.models.categories
import core.misc.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Fecha de actualización')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Fecha de creación')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de eliminación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('name', models.CharField(max_length=100, validators=[core.misc.utils.validate_char_field], verbose_name='Nombre')),
                ('image', models.ImageField(blank=True, upload_to=apps.categories.models.categories.upload_file_path, verbose_name='Imágen')),
                ('not_assigned', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categories',
            },
        ),
    ]
