name: Django CI/CD

on:
  push:
    branches: [ develop ]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Update
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/test.txt

      - name: Run Tests
        env:
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ACCESS_TOKEN_LIFETIME: ${{ secrets.ACCESS_TOKEN_LIFETIME }}
          REFRESH_TOKEN_LIFETIME: ${{ secrets.REFRESH_TOKEN_LIFETIME }}
          DEBUG: ${{ secrets.DEBUG }}
          DJANGO_SETTINGS_MODULE: ${{ secrets.DJANGO_SETTINGS_MODULE }}
        run: |
          coverage run manage.py test
  #          coverage xml -i
  #      - name: SonarCloud Scan
  #        uses: SonarSource/sonarcloud-github-action@master
  #        env:
  #          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
  #          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#  Deploy:
#    runs-on: ubuntu-latest
#    needs: Test
#    steps:
#      - name: Deploy to DigitalOcean DEV server
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.DEV_SERVER }}
#          username: ${{ secrets.DEV_USERNAME }}
#          password: ${{ secrets.DEV_PASSWORD }}
#          script: |
#  PostDeploy:
#    runs-on: ubuntu-latest
#    needs: Deploy
#    steps:
#      - name: Run NewMan test
#        uses: matt-ball/newman-action@master
#        with:
#          collection: ""
